In [48]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np


df=pd.read_csv('adv.csv')

X=df[["TV","Radio","Newspaper"]].values


Y=df['Sales'].values

print(X)
print(Y)

print(df.shape)



[[230.1  37.8  69.2]
 [ 44.5  39.3  45.1]
 [ 17.2  45.9  69.3]
 [151.5  41.3  58.5]
 [180.8  10.8  58.4]
 [  8.7  48.9  75. ]
 [ 57.5  32.8  23.5]
 [120.2  19.6  11.6]
 [  8.6   2.1   1. ]
 [199.8   2.6  21.2]
 [ 66.1   5.8  24.2]
 [214.7  24.    4. ]
 [ 23.8  35.1  65.9]
 [ 97.5   7.6   7.2]
 [204.1  32.9  46. ]
 [195.4  47.7  52.9]
 [ 67.8  36.6 114. ]
 [281.4  39.6  55.8]
 [ 69.2  20.5  18.3]
 [147.3  23.9  19.1]
 [218.4  27.7  53.4]
 [237.4   5.1  23.5]
 [ 13.2  15.9  49.6]
 [228.3  16.9  26.2]
 [ 62.3  12.6  18.3]
 [262.9   3.5  19.5]
 [142.9  29.3  12.6]
 [240.1  16.7  22.9]
 [248.8  27.1  22.9]
 [ 70.6  16.   40.8]
 [292.9  28.3  43.2]
 [112.9  17.4  38.6]
 [ 97.2   1.5  30. ]
 [265.6  20.    0.3]
 [ 95.7   1.4   7.4]
 [290.7   4.1   8.5]
 [266.9  43.8   5. ]
 [ 74.7  49.4  45.7]
 [ 43.1  26.7  35.1]
 [228.   37.7  32. ]
 [202.5  22.3  31.6]
 [177.   33.4  38.7]
 [293.6  27.7   1.8]
 [206.9   8.4  26.4]
 [ 25.1  25.7  43.3]
 [175.1  22.5  31.5]
 [ 89.7   9.9  35.7]
 [239.9  41.5

In [49]:
print(df[['TV','Radio','Newspaper','Sales']].isna().sum())
print(np.isfinite(df[['TV','Radio','Newspaper','Sales']].to_numpy()).all())
print(df[['TV','Radio','Newspaper','Sales']].dtypes)


TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64
True
TV           float64
Radio        float64
Newspaper    float64
Sales        float64
dtype: object


In [50]:
np.random.seed(42)



indices = np.random.permutation(len(X))

X_test = X[indices[:40]]
X_train = X[indices[40:200]]
Y_test = Y[indices[:40]]
Y_train = Y[indices[40:200]]


ones=np.ones((len(X_train),1))

X_AND_ONES=np.concatenate((ones,X_train),axis=1)



xt=X_AND_ONES.T



first_part=xt@X_AND_ONES


first_part_inv=np.linalg.inv(first_part)

second_part=xt@Y_train


model_weights=first_part_inv@second_part

print(model_weights)



[4.71412640e+00 5.45092708e-02 1.00945362e-01 4.33664682e-03]


In [51]:
import numpy as np

# Features and target
X = df[['TV', 'Radio', 'Newspaper']].values
Y = df['Sales'].values.reshape(-1,1)

# ✅ Add intercept column ONCE
ones = np.ones((len(X), 1))
X = np.hstack((ones, X))  

# Shuffle dataset
np.random.seed(42)
indices = np.random.permutation(len(X))

# 80/20 split
num_train = int(0.8 * len(X))

train_idx = indices[:num_train]
test_idx  = indices[num_train:]

X_train = X[train_idx]
Y_train = Y[train_idx]
X_test  = X[test_idx]
Y_test  = Y[test_idx]

# =========================
# NORMAL EQUATION
# =========================

Xt = X_train.T

W = np.linalg.inv(Xt @ X_train) @ Xt @ Y_train

print("Weights:\n", W)

# =========================
# PREDICTIONS
# =========================

Y_pred_test = X_test @ W
Y_pred_train = X_train @ W

# =========================
# ERRORS
# =========================

mse_test = np.mean((Y_test - Y_pred_test)**2)
rmse_test = np.sqrt(mse_test)

mse_train = np.mean((Y_train - Y_pred_train)**2)
rmse_train = np.sqrt(mse_train)

print("Test RMSE:", round(rmse_test,2))
print("Train RMSE:", round(rmse_train,2))


Weights:
 [[ 4.74378814e+00]
 [ 5.36094764e-02]
 [ 1.08856007e-01]
 [-2.03709034e-03]]
Test RMSE: 1.88
Train RMSE: 1.59
